[cube]
version = "1.0.0"
cluster-type = "small"
cluster-id = "sam-k8s"
debug-mode = true
closed-network = true
local-repository = "http://192.168.117.231:8080"
cert-validity-days = 36500

[kubernetes]
version ="1.20.2"
container-runtime = "containerd"
kube-proxy-mode="ipvs"
#vxlan-mode = true
  [kubernetes.etcd]
  ip = ["192.168.117.230"]
  encrypt-secret = true

[node-pool]
data-dir = "/data"

  [node-pool.security]
  ssh-user-id = "root"
  private-key-path = "id_rsa"

  [node-pool.master]
  ip = ["192.168.117.230"]
  internal-lb = "192.168.117.230"
  external-lb = "192.168.117.230"
  node-port-url = "192.168.117.230"
  node-portrange = "30000-32767"
  #isolated = true              
  #haproxy-install = false      

 [[node-pool.nodes]]
  ip = ["192.168.117.229"]

[shared-storage]
install = true
storage-ip="192.168.117.231"
volume-dir="/data/storage"
volume-size=100

[private-registry]
install = true
registry-ip = "192.168.117.231"
data-dir = "/data/harbor"
backup-file-path = "empty-files"
public-cert = false
  [private-registry.cert-file]
  ssl-certificate = ""
  ssl-certificate-key = ""

