package model

type ExpertYaml struct {
	KubeConfigDir              string        `default:"/etc/kubernetes" yaml:"kube_config_dir"`
	ManifestConfigDir          string        `yaml:"manifest_config_dir"`
	CertDir                    string        `yaml:"cert_dir"`
	MasterCertDir              string        `yaml:"master_cert_dir"`
	KubeAddonDir               string        `yaml:"kube_addon_dir"`
	AccountPrivateKey          string        `yaml:"account_private_key"`
	AccountKey                 string        `yaml:"account_key"`
	CaKey                      string        `yaml:"ca_key"`
	CaCert                     string        `yaml:"ca_cert"`
	APIKey                     string        `yaml:"api_key"`
	APICert                    string        `yaml:"api_cert"`
	APIKubeletClientKey        string        `yaml:"api_kubelet_client_key"`
	APIKubeletClientCert       string        `yaml:"api_kubelet_client_cert"`
	ProxyCaCert                string        `yaml:"proxy_ca_cert"`
	ProxyClientKey             string        `yaml:"proxy_client_key"`
	ProxyClientCert            string        `yaml:"proxy_client_cert"`
	DashboardCert              string        `yaml:"dashboard_cert"`
	DashboardKey               string        `yaml:"dashboard_key"`
	Kubeadminconfig            string        `yaml:"kubeadminconfig"`
	APIImage                   string        `yaml:"api_image"`
	ControllerImage            string        `yaml:"controller_image"`
	SchedulerImage             string        `yaml:"scheduler_image"`
	AuthMode                   string        `yaml:"auth_mode"`
	AuditLogEnable             bool          `yaml:"audit_log_enable"`
	EncryptSecret              bool          `yaml:"encrypt_secret"`
	KubernetesServiceIP        string        `yaml:"kubernetes_service_ip"`
	DNSIP                      string        `yaml:"dns_ip"`
	APISecurePort              int           `yaml:"api_secure_port"`
	APIInsecurePort            int           `yaml:"api_insecure_port"`
	EtcdPeerURLScheme          string        `yaml:"etcd_peer_url_scheme"`
	EtcdCaFile                 string        `yaml:"etcd_ca_file"`
	EtcdCertFile               string        `yaml:"etcd_cert_file"`
	EtcdKeyFile                string        `yaml:"etcd_key_file"`
	EtcdPeerCaFile             string        `yaml:"etcd_peer_ca_file"`
	EtcdPeerCertFile           string        `yaml:"etcd_peer_cert_file"`
	EtcdPeerKeyFile            string        `yaml:"etcd_peer_key_file"`
	EtcdHealthcheckCertFile    string        `yaml:"etcd_healthcheck_cert_file"`
	EtcdHealthcheckKeyFile     string        `yaml:"etcd_healthcheck_key_file"`
	HaproxyDir                 string        `yaml:"haproxy_dir"`
	HaproxyPort                int           `yaml:"haproxy_port"`
	HaproxyHealthCheckPort     int           `yaml:"haproxy_health_check_port"`
	ArchiveRepo                bool          `yaml:"archive_repo"`
	MetricsServer              bool          `yaml:"metrics_server"`
	AddonInstall               bool          `yaml:"addon_install"`
	PrometheusRulesLang        string        `yaml:"prometheus_rules_lang"`
	Ingress                    bool          `yaml:"ingress"`
	IngressHTTPExternalPort    int           `yaml:"ingress_http_external_port"`
	IngressHTTPSExternalPort   int           `yaml:"ingress_https_external_port"`
	YumProxy                   string        `yaml:"yum_proxy"`
	SubscriptionID             string        `yaml:"subscription_id"`
	ClientID                   string        `yaml:"client_id"`
	ClientSecret               string        `yaml:"client_secret"`
	TenantID                   string        `yaml:"tenant_id"`
	ResourceGroup              string        `yaml:"resource_group"`
	Location                   string        `yaml:"location"`
	VnetName                   string        `yaml:"vnet_name"`
	SubnetName                 string        `yaml:"subnet_name"`
	SecurityGroupName          string        `yaml:"security_group_name"`
	PrimaryAvailabilitySetName string        `yaml:"primary_availability_set_name"`
	RouteTableName             string        `yaml:"route_table_name"`
	EfsFileSystemID            string        `yaml:"efs_file_system_id"`
	StorageAccount             string        `yaml:"storage_account"`
	YumKubernetesURL           string        `yaml:"yum_kubernetes_url"`
	APISans                    []interface{} `yaml:"api_sans"`
	SingleVolumeDir            string        `yaml:"single_volume_dir"`
	SingleVolumeSize           int           `yaml:"single_volume_size"`
	SharedVolumeDir            string        `yaml:"shared_volume_dir"`
	StaticVolumeDir            string        `yaml:"static_volume_dir"`
	ClusterType                string        `yaml:"cluster_type"`
	Base64ControllerSecret     string        `yaml:"base64_controller_secret"`
	Base64MonitoringSecret     string        `yaml:"base64_monitoring_secret"`
	Base64ClusterSeq           string        `yaml:"base64_cluster_seq"`
	Base64ClusterID            string        `yaml:"base64_cluster_id"`
	StorageClassName           string        `yaml:"storage_class_name"`
	StorageType                string        `yaml:"storage_type"`
	SctpSupport                bool          `yaml:"sctp_support"`
	MultusInstall              bool          `yaml:"multus_install"`
	DeviceName                 string        `yaml:"device_name"`
	DeviceVen                  string        `yaml:"device_ven"`
	DeviceDev                  string        `yaml:"device_dev"`
	DeviceDriver               string        `yaml:"device_driver"`
	IngressType                string        `yaml:"ingress_type"`
	FsType                     string        `yaml:"fs_type"`
	MirrorCount                int           `yaml:"mirror_count"`
	PerfTier                   string        `yaml:"perf_tier"`
	VolumeBindingMode          string        `yaml:"volume_binding_mode"`
	IstioInstall               bool          `yaml:"istio_install"`
	DashboardPublicCert        bool          `yaml:"dashboard_public_cert"`
	HaType                     string        `yaml:"ha_type"`
	KubeSupportVersions        []string      `yaml:"kube_support_versions"`
	KubeFeatureGates           string        `yaml:"kube_feature_gates"`
	KubeproxyFeatureGates      string        `yaml:"kubeproxy_feature_gates"`
}
